### ISSUE TITLE
Error in solution

### ISSUE THREAD

**Issue by abbyesmith** [learn-co-curriculum/python-p3-attributes-and-properties#10]
### Canvas Link

https://learning.flatironschool.com/courses/6266/assignments/232404?module_item_id=544831

### Concern

I believe there is a copy/paste issue with the dogs solution:
`   def set_breed(self, job):
        if job in APPROVED_BREEDS:
            self._breed = job
        else:
            print("Breed must be in list of approved breeds.")

    breed = property(get_breed, set_breed)`

job should be breed.

**Comment by pgill97** [comment]
Changed job to breed.
