### ISSUE TITLE
examples under 'properties' missing __init__

### ISSUE THREAD

**Issue by jordandc20** [learn-co-curriculum/python-p3-attributes-and-properties#11]
### Canvas Link

https://learning.flatironschool.com/courses/6274/assignments/236163?module_item_id=554090

### Concern

i was trying out the examples under the "properties" header and they do not include the 
`    def __init__(self, name):
        self.name = name`
so i kept getting an error 
`TypeError: Human() takes no arguments`

**Comment by professor-ben** [comment]
This should be set now. Thanks for the report!
