### ISSUE TITLE
Attribute and Properties feedback

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/python-p3-attributes-and-properties#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195243?module_item_id=439029

### Concern

- “Attributes and Properties” module asks for Person name test to print “Name must be string under 25 characters.” but the test actually expects “Name must be string between 1 and 25 characters.”
- “Attributes and Properties” module should provide the “approved” lists. It’s pretty tedious to type in so many.

**Comment by professor-ben** [comment]
Hey Brandon,

The first was fixed in our last issues sprint- that will be pushed out in the next build release. We'll take care of point 2 today.

-Ben
