### ISSUE TITLE
Tests require students to not use __init__() contrary to README examples

### ISSUE THREAD

**Issue by lantzbuilds** [learn-co-curriculum/python-p3-attributes-and-properties#7]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195243?module_item_id=439029

### Concern

The README examples for how to write classes with properties all show a class with an `__init__()` method, however the tests for the exercises only complete if the students' classes don't use `__init__`.  I think this could be quite confusing to a beginner and require extra explanation.

### Suggested Changes

Could tests be rewritten to pass with __init__ in student code?  Or drop hint in deliverables that __init__ isn't required here and why?

**Comment by professor-ben** [comment]
working through this now. thanks!
