### ISSUE TITLE
confusion on property

### ISSUE THREAD

**Issue by DavidWolff218** [learn-co-curriculum/python-p3-attributes-and-properties#8]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195243?module_item_id=439029

### Concern

<img width="923" alt="Screen Shot 2022-12-20 at 5 04 30 PM" src="https://user-images.githubusercontent.com/60520496/209023437-d4e972a3-3aaf-495e-bc8b-df7378c9e988.png">

When trying to break my code, I couldn't get the set_breed error to print out if I passed in a breed that wasnt approved on the list on instantiation. Eventually we were able to get that to work by changing the code to look like this...

<img width="665" alt="Screen Shot 2022-12-21 at 5 37 33 PM" src="https://user-images.githubusercontent.com/60520496/209023647-5b184aec-7873-4bbf-bfe9-c083b61bafc2.png">

Though this syntax was new to me.

### Suggested Changes

Given the materials and readings up till this point, I was under the assumption that the set_breed would run and block a new instance from being made if I passed in something that didnt fit. But to get that to work we had to work out some syntax that hadnt been seen yet. So I guess just trying to clear up what is possible with what we have learned thus far and what set_breed is doing

**Comment by professor-ben** [comment]
I made a lot of changes to clear this up. There are no more definitions in `__init__` methods here. Additionally, there is an (old) note that talks about when we want to define with `__init__` and when we don't.

Made some Pipfile and pytest updates as well.

Thanks,
Ben
