### ISSUE TITLE
Typo in example code 

### ISSUE THREAD

**Issue by SWhalley1130** [learn-co-curriculum/python-p3-attributes-and-properties#9]
### Canvas Link

https://learning.flatironschool.com/courses/6266/assignments/232404?module_item_id=544831

### Concern

Example uses 'in' where 'is' should be used. 
![image](https://user-images.githubusercontent.com/98498031/225437131-4de698ae-2d91-47ad-94e1-d2066c7df4e4.png)

**Comment by professor-ben** [comment]
Hello,

Apologies if this is a confusing bit of code- it's meant to check if the data type of `age` is in the tuple `(int, float)`. We are looking to use `in` here, as written.

Thanks,
Ben
